spring:
  application:
    name: extractionservice
  mvc:
    async:
      request-timeout: 120000
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
      embedding:
        model: nomic-embed-text

  datasource:
    url: jdbc:postgresql://localhost:5432/recruitment_workflow
    username: postgres
    password: root